In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [ ]:
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\dataset_v1.27.csv')

In [49]:
df.columns

Index(['invoiceDate', 'quarter', 'month', 'year', 'day_of_week',
       'day_of_month', 'day_of_year', 'week_of_year', 'salesDetails_id',
       'billAmount', 'stockistId', 'chemistId', 'hqId', 'regionId', 'qty',
       'free', 'rate', 'amount', 'productId', 'divisionId', 'mrp',
       'packingTypeId'],
      dtype='object')

In [50]:
# df = dff.drop(['salesYear', 'salesMonth', 'InvoiceWeek'],axis=1)

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248420 entries, 0 to 248419
Data columns (total 22 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   invoiceDate      248420 non-null  object
 1   quarter          248420 non-null  int64
 2   month            248420 non-null  int64
 3   year             248420 non-null  int64
 4   day_of_week      248420 non-null  int64
 5   day_of_month     248420 non-null  int64
 6   day_of_year      248420 non-null  int64
 7   week_of_year     248420 non-null  int64
 8   salesDetails_id  248420 non-null  int64
 9   billAmount       248420 non-null  int64
 10  stockistId       178196 non-null  float64
 11  chemistId        70224 non-null   float64
 12  hqId             225041 non-null  float64
 13  regionId         225041 non-null  float64
 14  qty              248420 non-null  int64
 15  free             248420 non-null  int64
 16  rate             248420 non-null  float64
 17  amount           248420 non-null  float64
 18  productId        226558 non-null  float64
 19  divisionId       226558 non-null  float64
 20  mrp              226558 non-null  float64
 21  packingTypeId    226558 non-null  float64
dtypes: float64(10), int64(11), object(1)
memory usage: 41.7+ MB

In [52]:
df

,invoiceDate,quarter,month,year,day_of_week,day_of_month,day_of_year,week_of_year,salesDetails_id,billAmount,...,hqId,regionId,qty,free,rate,amount,productId,divisionId,mrp,packingTypeId
0,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,200,0,52.07,10414.0,168.0,3.0,85.50,28.0
1,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,30,0,333.26,9997.8,261.0,3.0,486.00,28.0
2,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,30,0,25.46,763.8,218.0,3.0,43.20,28.0
3,7/6/2022,3,7,2022,4,6,187,28,594,29491,...,15.0,1.0,50,0,48.60,2430.0,227.0,3.0,79.20,42.0
4,7/6/2022,3,7,2022,4,6,187,28,594,29491,...,15.0,1.0,30,0,46.09,1382.7,71.0,3.0,79.16,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248415,1/8/2025,1,1,2025,4,8,8,2,195141,24709,...,45.0,1.0,40,0,48.60,1944.0,NaN,NaN,NaN,NaN
248416,1/8/2025,1,1,2025,4,8,8,2,195142,24709,...,45.0,1.0,30,0,101.82,3054.6,NaN,NaN,NaN,NaN
248417,11/4/2022,4,11,2022,6,4,308,45,74442,27073,...,45.0,1.0,20,0,104.14,2082.8,265.0,3.0,162.00,28.0
248418,11/7/2022,4,11,2022,2,7,311,46,74558,17185,...,45.0,1.0,40,0,104.14,4165.6,265.0,3.0,162.00,28.0
248419,11/12/2022,4,11,2022,7,12,316,46,75341,3600,...,14.0,1.0,50,0,64.29,3214.5,13.0,1.0,158.40,42.0

In [53]:
df1 = df[(df['chemistId'].notnull()) & (df['stockistId'].isnull()) |
         (df['chemistId'].isnull()) & (df['stockistId'].notnull())]

df2 = df[(df['chemistId'].notnull()) & (df['stockistId'].notnull())]

df3 = df[(df['chemistId'].isnull()) & (df['stockistId'].isnull())]

In [54]:
df1

,invoiceDate,quarter,month,year,day_of_week,day_of_month,day_of_year,week_of_year,salesDetails_id,billAmount,...,hqId,regionId,qty,free,rate,amount,productId,divisionId,mrp,packingTypeId
0,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,200,0,52.07,10414.0,168.0,3.0,85.50,28.0
1,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,30,0,333.26,9997.8,261.0,3.0,486.00,28.0
2,6/23/2023,2,6,2023,6,23,174,25,195,140385,...,1.0,1.0,30,0,25.46,763.8,218.0,3.0,43.20,28.0
3,7/6/2022,3,7,2022,4,6,187,28,594,29491,...,15.0,1.0,50,0,48.60,2430.0,227.0,3.0,79.20,42.0
4,7/6/2022,3,7,2022,4,6,187,28,594,29491,...,15.0,1.0,30,0,46.09,1382.7,71.0,3.0,79.16,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248415,1/8/2025,1,1,2025,4,8,8,2,195141,24709,...,45.0,1.0,40,0,48.60,1944.0,NaN,NaN,NaN,NaN
248416,1/8/2025,1,1,2025,4,8,8,2,195142,24709,...,45.0,1.0,30,0,101.82,3054.6,NaN,NaN,NaN,NaN
248417,11/4/2022,4,11,2022,6,4,308,45,74442,27073,...,45.0,1.0,20,0,104.14,2082.8,265.0,3.0,162.00,28.0
248418,11/7/2022,4,11,2022,2,7,311,46,74558,17185,...,45.0,1.0,40,0,104.14,4165.6,265.0,3.0,162.00,28.0
248419,11/12/2022,4,11,2022,7,12,316,46,75341,3600,...,14.0,1.0,50,0,64.29,3214.5,13.0,1.0,158.40,42.0

In [55]:
# find those stockists/chemists (refer them using their respective ids), whose region,hq,city ids are missing.

def null(df1):
    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['regionId', 'hqId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['stockistId', 'chemistId']].drop_duplicates().reset_index(drop=True)

    return result

# def null(df1):
#     return df1[df1[['regionId', 'hqId', 'cityId']].isna().any(axis=1)]



new_df = null(df1)
print(new_df.to_string())

    stockistId  chemistId
0         95.0        NaN
1        168.0        NaN
2        197.0        NaN
3        100.0        NaN
4          NaN     3621.0
5          NaN     5784.0
6          NaN      732.0
7          NaN     1065.0
8          NaN      795.0
9          NaN     5473.0
10         NaN     5363.0
11         NaN     5722.0
12         NaN     5417.0
13         NaN    11046.0
14         NaN     3343.0
15         NaN     1414.0
16         NaN     5735.0
17         NaN     6505.0
18         NaN     5440.0
19         NaN     5486.0
20         NaN     3525.0
21         NaN      963.0
22         NaN      841.0
23         NaN      757.0
24         NaN      829.0
25         NaN      785.0
26         NaN    10687.0
27         NaN      982.0
28         NaN    11125.0
29         NaN    11025.0
30         NaN    10994.0
31         NaN    11353.0
32         NaN      912.0
33         NaN    10654.0
34         NaN    11416.0
35         NaN    11410.0
36         NaN    11062.0
37         NaN     8734.0
38         NaN    10961.0
39         NaN    11324.0
40         NaN     5143.0
41         NaN     3263.0
42         NaN      927.0
43         NaN    11116.0
44         NaN      923.0
45         NaN     1707.0
46         NaN     6310.0

In [56]:
def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['regionId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['stockistId', 'regionId']].drop_duplicates()#.reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

      stockistId  regionId
211         95.0       NaN
303        168.0       NaN
354        197.0       NaN
1032       100.0       NaN
6090         NaN       NaN

In [57]:
def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['hqId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['stockistId', 'hqId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

   stockistId  hqId
0        95.0   NaN
1       168.0   NaN
2       197.0   NaN
3       100.0   NaN
4         NaN   NaN

In [58]:
# def null(df1):

#     # Filter rows where any of the key location IDs are missing
#     missing = df1[df1[['cityId']].isna().any(axis=1)]

#     # Get unique combinations of stockistId and chemistId with missing info
#     result = missing[['stockistId', 'cityId']].drop_duplicates().reset_index(drop=True)

#     return result
# new_df = null(df1)
# print(new_df.to_string())

In [72]:
def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['regionId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['chemistId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

# new_df = df1[df1.notnull()]
flat_list = new_df.values.flatten().tolist()
print(flat_list)

    chemistId
0         NaN
1      3621.0
2      5784.0
3       732.0
4      1065.0
5       795.0
6      5473.0
7      5363.0
8      5722.0
9      5417.0
10    11046.0
11     3343.0
12     1414.0
13     5735.0
14     6505.0
15     5440.0
16     5486.0
17     3525.0
18      963.0
19      841.0
20      757.0
21      829.0
22      785.0
23    10687.0
24      982.0
25    11125.0
26    11025.0
27    10994.0
28    11353.0
29      912.0
30    10654.0
31    11416.0
32    11410.0
33    11062.0
34     8734.0
35    10961.0
36    11324.0
37     5143.0
38     3263.0
39      927.0
40    11116.0
41      923.0
42     1707.0
43     6310.0
[nan, 3621.0, 5784.0, 732.0, 1065.0, 795.0, 5473.0, 5363.0, 5722.0, 5417.0, 11046.0, 3343.0, 1414.0, 5735.0, 6505.0, 5440.0, 5486.0, 3525.0, 963.0, 841.0, 757.0, 829.0, 785.0, 10687.0, 982.0, 11125.0, 11025.0, 10994.0, 11353.0, 912.0, 10654.0, 11416.0, 11410.0, 11062.0, 8734.0, 10961.0, 11324.0, 5143.0, 3263.0, 927.0, 11116.0, 923.0, 1707.0, 6310.0]

In [60]:
def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['hqId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['chemistId', 'hqId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

    chemistId  hqId
0         NaN   NaN
1      3621.0   NaN
2      5784.0   NaN
3       732.0   NaN
4      1065.0   NaN
5       795.0   NaN
6      5473.0   NaN
7      5363.0   NaN
8      5722.0   NaN
9      5417.0   NaN
10    11046.0   NaN
11     3343.0   NaN
12     1414.0   NaN
13     5735.0   NaN
14     6505.0   NaN
15     5440.0   NaN
16     5486.0   NaN
17     3525.0   NaN
18      963.0   NaN
19      841.0   NaN
20      757.0   NaN
21      829.0   NaN
22      785.0   NaN
23    10687.0   NaN
24      982.0   NaN
25    11125.0   NaN
26    11025.0   NaN
27    10994.0   NaN
28    11353.0   NaN
29      912.0   NaN
30    10654.0   NaN
31    11416.0   NaN
32    11410.0   NaN
33    11062.0   NaN
34     8734.0   NaN
35    10961.0   NaN
36    11324.0   NaN
37     5143.0   NaN
38     3263.0   NaN
39      927.0   NaN
40    11116.0   NaN
41      923.0   NaN
42     1707.0   NaN
43     6310.0   NaN

In [ ]:
#####################################################################################

def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['regionId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['chemistId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

# new_df = df1[df1.notnull()]
flat_list = new_df.values.flatten().tolist()
print(flat_list)

    chemistId
0         NaN
1      3621.0
2      5784.0
3       732.0
4      1065.0
5       795.0
6      5473.0
7      5363.0
8      5722.0
9      5417.0
10    11046.0
11     3343.0
12     1414.0
13     5735.0
14     6505.0
15     5440.0
16     5486.0
17     3525.0
18      963.0
19      841.0
20      757.0
21      829.0
22      785.0
23    10687.0
24      982.0
25    11125.0
26    11025.0
27    10994.0
28    11353.0
29      912.0
30    10654.0
31    11416.0
32    11410.0
33    11062.0
34     8734.0
35    10961.0
36    11324.0
37     5143.0
38     3263.0
39      927.0
40    11116.0
41      923.0
42     1707.0
43     6310.0
[nan, 3621.0, 5784.0, 732.0, 1065.0, 795.0, 5473.0, 5363.0, 5722.0, 5417.0, 11046.0, 3343.0, 1414.0, 5735.0, 6505.0, 5440.0, 5486.0, 3525.0, 963.0, 841.0, 757.0, 829.0, 785.0, 10687.0, 982.0, 11125.0, 11025.0, 10994.0, 11353.0, 912.0, 10654.0, 11416.0, 11410.0, 11062.0, 8734.0, 10961.0, 11324.0, 5143.0, 3263.0, 927.0, 11116.0, 923.0, 1707.0, 6310.0]

In [61]:
def null(df1):

    # Filter rows where any of the key location IDs are missing
    missing = df1[df1[['cityId']].isna().any(axis=1)]

    # Get unique combinations of stockistId and chemistId with missing info
    result = missing[['chemistId', 'cityId']].drop_duplicates().reset_index(drop=True)

    return result
new_df = null(df1)
print(new_df.to_string())

KeyError: "None of [Index(['cityId'], dtype='object')] are in the [columns]"