In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\dataset_v4.05.csv')

In [3]:
# df.drop(['day_of_week', 'day_of_month', 'day_of_year', 'week_of_year', 'quarter', 'contents', 'month', 'year'],axis=1,inplace=True)

In [4]:
df.columns

Index(['salesId', 'invoiceId', 'invoiceDate', 'stockistId', 'chemistId',
       'billAmount', 'salesDetails_Id', 'productCode', 'productName',
       'productId', 'mrp', 'rate', 'batch', 'expiryDate', 'qty', 'free',
       'amount', 'cashDiscountPercentage', 'productDiscountPercentage',
       'productDiscount', 'extraSchemePercentage', 'extraScheme',
       'taxableAmount', 'sgst', 'sgstAmount', 'cgst', 'cgstAmount', 'cess',
       'cessAmount', 'ptr', 'pts', 'hsn', 'contents', 'packingTypeId',
       'divisionId', 'cityId', 'regionId', 'customerName', 'addressId', 'hqId',
       'categoryId', 'chemistTypeId'],
      dtype='object')

In [5]:
df.isna().sum()

salesId                           0
invoiceId                         0
invoiceDate                       0
stockistId                    25725
chemistId                    100720
billAmount                        0
salesDetails_Id                   0
productCode                       0
productName                       0
productId                         0
mrp                               0
rate                              0
batch                             0
expiryDate                        0
qty                               0
free                              0
amount                            0
cashDiscountPercentage            0
productDiscountPercentage         0
productDiscount                   0
extraSchemePercentage             0
extraScheme                       0
taxableAmount                     0
sgst                              0
sgstAmount                        0
cgst                              0
cgstAmount                        0
cess                              0
cessAmount                        0
ptr                               0
pts                               0
hsn                               0
contents                          0
packingTypeId                     0
divisionId                        0
cityId                        10987
regionId                      33074
customerName                      0
addressId                     10801
hqId                           7349
categoryId                   105495
chemistTypeId                105484
dtype: int64

In [6]:
df['stockistId'] = df['stockistId'].round().astype('Int64')    # does not give error due to Int
df['chemistId'] = df['chemistId'].round().astype('Int64')    # does not give error due to Int

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126445 entries, 0 to 126444
Data columns (total 42 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   salesId                    126445 non-null  int64
 1   invoiceId                  126445 non-null  object
 2   invoiceDate                126445 non-null  object
 3   stockistId                 100720 non-null  Int64
 4   chemistId                  25725 non-null   Int64
 5   billAmount                 126445 non-null  int64
 6   salesDetails_Id            126445 non-null  int64
 7   productCode                126445 non-null  object
 8   productName                126445 non-null  object
 9   productId                  126445 non-null  int64
 10  mrp                        126445 non-null  float64
 11  rate                       126445 non-null  float64
 12  batch                      126445 non-null  object
 13  expiryDate                 126445 non-null  object
 14  qty                        126445 non-null  int64
 15  free                       126445 non-null  int64
 16  amount                     126445 non-null  float64
 17  cashDiscountPercentage     126445 non-null  int64
 18  productDiscountPercentage  126445 non-null  int64
 19  productDiscount            126445 non-null  int64
 20  extraSchemePercentage      126445 non-null  int64
 21  extraScheme                126445 non-null  int64
 22  taxableAmount              126445 non-null  float64
 23  sgst                       126445 non-null  float64
 24  sgstAmount                 126445 non-null  float64
 25  cgst                       126445 non-null  float64
 26  cgstAmount                 126445 non-null  float64
 27  cess                       126445 non-null  int64
 28  cessAmount                 126445 non-null  int64
 29  ptr                        126445 non-null  float64
 30  pts                        126445 non-null  float64
 31  hsn                        126445 non-null  int64
 32  contents                   126445 non-null  object
 33  packingTypeId              126445 non-null  int64
 34  divisionId                 126445 non-null  int64
 35  cityId                     115458 non-null  float64
 36  regionId                   93371 non-null   float64
 37  customerName               126445 non-null  object
 38  addressId                  115644 non-null  float64
 39  hqId                       119096 non-null  float64
 40  categoryId                 20950 non-null   float64
 41  chemistTypeId              20961 non-null   float64
dtypes: Int64(2), float64(16), int64(16), object(8)
memory usage: 40.8+ MB

In [8]:
df.shape

(126445, 42)

In [9]:
df

,salesId,invoiceId,invoiceDate,stockistId,chemistId,billAmount,salesDetails_Id,productCode,productName,productId,...,contents,packingTypeId,divisionId,cityId,regionId,customerName,addressId,hqId,categoryId,chemistTypeId
0,193,DB-T-1052,7/14/2021,<NA>,1758,124604,1418,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
1,631,DB-T-1179,7/26/2021,<NA>,1758,213574,4720,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
2,304,DB-T-1084,6/29/2022,<NA>,1758,75218,2182,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
3,1388,DB-T-1394,7/25/2022,<NA>,1758,151206,9994,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
4,2543,DB-T-1726,9/14/2021,<NA>,1758,201934,18491,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126440,56847,DB-T-4349,1/28/2025,<NA>,5469,13680,142754,9,BIO-ANXIT,168,...,Flupentixol 0.5 mg + Melitracen 10 mg Tab,28,3,22.0,NaN,MDC MEDI SHOP,82869.0,1.0,259.0,1.0
126441,9689,DB-T-3506,12/22/2023,<NA>,5046,9000,70154,25,F-DIN-180,220,...,Fexofenadine 180 Mg Tab,28,1,22.0,NaN,DR.NAJABHAI RAMBHAI JALU,82446.0,34.0,NaN,NaN
126442,9689,DB-T-3506,12/22/2023,<NA>,5046,9000,70156,12,BIOKET SOAP,215,...,Ketoconazole 2% 75 GM SOAP,35,1,22.0,NaN,DR.NAJABHAI RAMBHAI JALU,82446.0,34.0,NaN,NaN
126443,6703,DB-T-2831,11/23/2022,<NA>,2425,1568,48809,38,R-ZOLE-DSR,235,...,Rabeprazole Sodium 20 mg Tab + Demperidone 30 ...,42,3,68.0,NaN,SHIVSAKTI MEDICAL,73053.0,9.0,259.0,1.0
126444,44310,DB-T-588,5/15/2024,118,<NA>,31826,106633,12,BIOKET SOAP,215,...,Ketoconazole 2% 75 GM SOAP,35,1,22.0,1.0,YAJAT MEDICINES,56158.0,1.0,NaN,NaN

In [10]:
df_filtered = df[df['productId'] == 166].copy()

In [11]:
df_filtered

,salesId,invoiceId,invoiceDate,stockistId,chemistId,billAmount,salesDetails_Id,productCode,productName,productId,...,contents,packingTypeId,divisionId,cityId,regionId,customerName,addressId,hqId,categoryId,chemistTypeId
0,193,DB-T-1052,7/14/2021,<NA>,1758,124604,1418,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
1,631,DB-T-1179,7/26/2021,<NA>,1758,213574,4720,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
2,304,DB-T-1084,6/29/2022,<NA>,1758,75218,2182,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
3,1388,DB-T-1394,7/25/2022,<NA>,1758,151206,9994,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
4,2543,DB-T-1726,9/14/2021,<NA>,1758,201934,18491,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4002,55901,DB-T-3954,1/3/2025,<NA>,5676,20832,136260,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,STAR MEDICINES,83076.0,1.0,258.0,1.0
4009,13340,DB-T-660,5/25/2022,<NA>,1065,350986,96909,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,22.0,NaN,S.R MEDISALES,65454.0,1.0,NaN,NaN
5240,14276,DB-T-927,7/3/2021,<NA>,1758,143560,103454,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,582.0,NaN,SAMRAT MEDICAL,69657.0,20.0,258.0,1.0
5603,50785,DB-T-611,5/16/2024,129,<NA>,4060,120821,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,27.0,1.0,SANJIVANI MEDICINES,56169.0,11.0,NaN,NaN
11967,4922,DB-T-2407,10/13/2022,<NA>,6505,3672,35795,PS35VE5K,BIOBETA-AM,166,...,Amlodipine 5 mg Tab + Metoprolol Succinate 50 ...,28,3,552.0,NaN,GALAXY MEDICAL,84561.0,8.0,259.0,1.0

In [12]:
agg_df = df.groupby('productId').agg(
    invoice_count=('invoiceDate', 'count'),
    total_qty=('qty', 'sum'),
    total_amount=('amount', 'sum'),
    total_billAmount=('billAmount', 'sum')
).reset_index()

# Optional: Sort by invoice_count and pick top N to avoid overcrowding
top_n = 156
# agg_df = agg_df.sort_values('invoice_count', ascending=False).head(top_n)

In [13]:
agg_df

     productId  invoice_count  total_qty  total_amount  total_billAmount
0            1           1910     116535    8125711.71         162656499
1            2           1515      63598    5134329.73          94897319
2            8           2061     141851    6359431.85         157397715
3           11            300       3012     327943.03          22570380
4           12            106       1250     153282.41           5409390
..         ...            ...        ...           ...               ...
133      17615            127       4480     788927.60          32241811
134      17616             43       2201     784258.65           9038110
135      17617             40       1117     578134.18           7131905
136      17624              7        220      28144.60            868831
137      17625              2        105      28983.40             34920

[138 rows x 5 columns]