## Prerequisites

!pip install pandas numpy matplotlib

## how to use cleanData

#### step 0 : import necessary libraries

In [38]:
import pandas as pd
import numpy as np

#### step 1 : you need to import cleanData class from clean_data module

In [39]:
from clean_data import cleanData

#### step 2: load dataframe

replace '../dataset/data.csv' with the actual path to your CSV file.

In [40]:
df = pd.read_csv(r'C:\Kenil Ramani\QB\GoalBot\CSV\dataset_v1.29.csv')

#### step 3: initialize cleanData object with your dataframe

In [41]:
cd = cleanData(df)

## here we go....

you can easily play with your dataframe

--- Filtering data for productId 165 ---

In [48]:
cd.filter_productsby(productId=165)

how to extract the resultant dataframe

In [55]:
cd.data_df

,salesYear,salesMonth,InvoiceWeek,invoiceDate,salesDetails_id,billAmount,stockistId,chemistId,categoryId,hqId,regionId,cityId,mrp,qty,free,rate,amount,productId,divisionId,packingTypeId
56,2021,1,1,2021-01-01,39325,35465,93.0,NaN,NaN,17.0,1.0,21.0,90.0,0,280,57.86,0.0,165,3,28
61,2021,1,1,2021-01-01,39024,27799,115.0,NaN,NaN,1.0,1.0,22.0,90.0,50,0,57.86,2893.0,165,3,28
84,2021,1,1,2021-01-02,39655,18714,102.0,NaN,NaN,15.0,1.0,14.0,90.0,20,0,57.86,1157.2,165,3,28
143,2021,1,1,2021-01-02,39555,199027,105.0,NaN,NaN,8.0,1.0,15.0,90.0,150,0,57.86,8679.0,165,3,28
255,2021,1,2,2021-01-05,40571,143496,111.0,NaN,NaN,8.0,1.0,15.0,90.0,40,0,57.86,2314.4,165,3,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127056,2025,1,3,2025-01-15,141306,127695,98.0,NaN,NaN,18.0,1.0,67.0,108.0,50,0,69.43,3471.5,165,3,28
127043,2025,1,3,2025-01-15,141304,9936,177.0,NaN,NaN,8.0,1.0,552.0,108.0,20,0,69.43,1388.6,165,3,28
127305,2025,1,3,2025-01-17,141566,229536,176.0,NaN,NaN,8.0,1.0,15.0,108.0,100,0,69.43,6943.0,165,3,28
127425,2025,1,3,2025-01-18,141670,188156,101.0,NaN,NaN,1.0,1.0,22.0,108.0,20,0,69.43,1388.6,165,3,28
127509,2025,1,4,2025-01-20,141870,128185,98.0,NaN,NaN,18.0,1.0,67.0,108.0,60,0,69.43,4165.8,165,3,28

if you wish to filter by customer_type

In [50]:
cd.filter_productsby(customerType='stockist')

--- filtering data for productId 165 and 'stockist' ---

In [52]:
cd.filter_productsby(165, 'stockist')

you can apply multiple filters with multiple values

In [54]:
cd.filter_productsby([165,26,283], 'stockist')

## you can aggregate sales

by specifying frequency

'daily',    
'weekly',   
'weekly_monday' (aggregates sales to the Monday of each week)   
'monthly'   
'monthly_first' 
'yearly'

In [47]:
cd.aggregate_sales(
    frequency='weekly_monday'
)

NameError: name 'group_by_frequency' is not defined

In [ ]:
cd.data_df

    invoiceDate    qty      amount
0    2020-12-27  12065   865007.62
1    2021-01-03  24007  1540581.99
2    2021-01-10  18099  1059954.02
3    2021-01-17  28225  2079317.50
4    2021-01-24  23548  1558613.19
..          ...    ...         ...
210  2025-01-05  41713  3333616.37
211  2025-01-12  29610  2434233.77
212  2025-01-19  42495  3276539.06
213  2025-01-26  39499  3676724.64
214  2025-02-02  14011  1106345.34

[215 rows x 3 columns]

## likewise you can process outliers

In [ ]:
#remove outliers
cd.process_outliers(
    column='amount',
    multiplier=1.5,
    q1=0.15,
    q3=0.95,
    strategy='cap'
)

amount ---> Q1: 1603810.586, Q3: 3685209.9680000003, IQR: 2081399.3820000004
Lower Bound: -1518288.487000001, Upper Bound: 6807309.041000001
Outliers in 'amount' have been capped.

In [ ]:
cd.data_df

    invoiceDate    qty      amount
0    2020-12-27  12065   865007.62
1    2021-01-03  24007  1540581.99
2    2021-01-10  18099  1059954.02
3    2021-01-17  28225  2079317.50
4    2021-01-24  23548  1558613.19
..          ...    ...         ...
210  2025-01-05  41713  3333616.37
211  2025-01-12  29610  2434233.77
212  2025-01-19  42495  3276539.06
213  2025-01-26  39499  3676724.64
214  2025-02-02  14011  1106345.34

[215 rows x 3 columns]